export const PROJECT_CATEGORIES = [
  { value: "crops", label: "Crops & Grains", icon: "🌾" },
  { value: "poultry", label: "Poultry Farming", icon: "🐔" },
  { value: "livestock", label: "Livestock", icon: "🐄" },
  { value: "processing", label: "Food Processing", icon: "🏭" },
  { value: "equipment", label: "Farm Equipment", icon: "🚜" },
] as const

export const NIGERIAN_STATES = [
  "Abia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Edo",
  "Ekiti",
  "Enugu",
  "FCT",
  "Gombe",
  "Imo",
  "Jigawa",
  "Kaduna",
  "Kano",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Nasarawa",
  "Niger",
  "Ogun",
  "Ondo",
  "Osun",
  "Oyo",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara",
] as const

export const RISK_LEVELS = [
  { value: "low", label: "Low Risk", color: "text-green-600 bg-green-100" },
  { value: "medium", label: "Medium Risk", color: "text-yellow-600 bg-yellow-100" },
  { value: "high", label: "High Risk", color: "text-red-600 bg-red-100" },
] as const
